// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddDownload'](arg1, arg2, arg3, arg4);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function GetAllDownloads() {
  return window['go']['main']['App']['GetAllDownloads']();
}

export function GetDefaultDownloadDir() {
  return window['go']['main']['App']['GetDefaultDownloadDir']();
}

export function GetDownload(arg1) {
  return window['go']['main']['App']['GetDownload'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function ProbeURL(arg1) {
  return window['go']['main']['App']['ProbeURL'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['main']['App']['RemoveDownload'](arg1);
}

export function RemoveDownloadAndFile(arg1) {
  return window['go']['main']['App']['RemoveDownloadAndFile'](arg1);
}

export function RetryDownload(arg1) {
  return window['go']['main']['App']['RetryDownload'](arg1);
}

export function RevealInFolder(arg1) {
  return window['go']['main']['App']['RevealInFolder'](arg1);
}

export function SearchHistory(arg1) {
  return window['go']['main']['App']['SearchHistory'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}
