// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddDownload(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<domain.Download>;

export function CancelDownload(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteHistoryEntry(arg1:string):Promise<void>;

export function GetAllDownloads():Promise<Array<domain.Download>>;

export function GetDefaultDownloadDir():Promise<string>;

export function GetDownload(arg1:string):Promise<domain.Download>;

export function GetHistory():Promise<Array<domain.HistoryEntry>>;

export function GetSettings():Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function ProbeURL(arg1:string):Promise<Record<string, any>>;

export function RemoveDownload(arg1:string):Promise<void>;

export function RemoveDownloadAndFile(arg1:string):Promise<void>;

export function RetryDownload(arg1:string):Promise<void>;

export function RevealInFolder(arg1:string):Promise<void>;

export function SearchHistory(arg1:string):Promise<Array<domain.HistoryEntry>>;

export function SelectDirectory():Promise<string>;

export function StartDownload(arg1:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;
